name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
        ref: ["master"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: MLton/mlton
          ref: refs/heads/${{ matrix.ref }}

      - run: |
          sudo apt-get update
          sudo apt-get install libgmp-dev qemu-user-static

      - run: |
          mkdir boot && cd boot
          curl -sOL https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117-1.amd64-linux-glibc2.31.tgz
          tar xzf mlton-20210117-1.amd64-linux-glibc2.31.tgz --exclude='*/share'
          mv mlton-20210117-1.amd64-linux-glibc2.31/* .
          rmdir mlton-20210117-1.amd64-linux-glibc2.31

      - run: |
          curl -sOL https://more.musl.cc/x86_64-linux-musl/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
          sudo cp -fpr aarch64-linux-musl-cross/* /usr/local/

      - run: |
          curl -sOL https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz
          tar -xf gmp-6.3.0.tar.xz
          cd gmp-6.3.0
          ./configure --disable-shared --build=x86_64-linux-gnu --host=aarch64-linux-musl
          make
          # make check
          sudo make install

      - run: PATH="$(pwd)/boot/bin:$PATH" make -C runtime LDFLAGS=-static TARGET=aarch64-linux-musl TARGET_ARCH=arm64 WITH_GMP_DIR=/usr/local gdtoa/arithchk gdtoa/qnan gen/gen-types
  
      - run: qemu-aarch64-static runtime/gen/gen-types ml-types.h > runtime/gen/ml-types.h
      - run: cp -fpR runtime/gen/ml-types.h runtime/ml-types.h
      
      - run: qemu-aarch64-static runtime/gen/gen-types c-types.h > runtime/gen/c-types.h
      - run: cp -fpR runtime/gen/c-types.h runtime/c-types.h
      
      - run: qemu-aarch64-static runtime/gen/gen-types c-types.sml > runtime/gen/c-types.sml
      
      - run: qemu-aarch64-static runtime/gdtoa/arithchk > runtime/gdtoa/arith.h
      - run: qemu-aarch64-static runtime/gdtoa/qnan > runtime/gdtoa/gd_qnan.h

      - run: PATH="$(pwd)/boot/bin:$PATH" make LDFLAGS=-static TARGET=aarch64-linux-musl TARGET_ARCH=arm64 WITH_GMP_DIR=/usr/local dirs
      - run: PATH="$(pwd)/boot/bin:$PATH" make LDFLAGS=-static TARGET=aarch64-linux-musl TARGET_ARCH=arm64 WITH_GMP_DIR=/usr/local runtime
      - run: sudo cp -fpR build/lib/mlton/targets/aarch64-linux-musl boot/lib/mlton/targets/

      - run: PATH="$(pwd)/boot/bin:$PATH" make LDFLAGS=-static TARGET=aarch64-linux-musl TARGET_ARCH=arm64 WITH_GMP_DIR=/usr/local MLTON_COMPILE_ARGS="-cc-opt -I/usr/local/include" all
