name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
        ref: ["master"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: MLton/mlton
          ref: refs/heads/${{ matrix.ref }}

      - name: Install system prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libgmp-dev qemu-user-static

      - name: Install bootstrap mlton
        run: |
          mkdir boot && cd boot
          curl -sOL https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117-1.amd64-linux-glibc2.31.tgz
          tar xzf mlton-20210117-1.amd64-linux-glibc2.31.tgz --exclude='*/share'
          rm mlton-20210117-1.amd64-linux-glibc2.31.tgz
          mv mlton-20210117-1.amd64-linux-glibc2.31/* .
          rmdir mlton-20210117-1.amd64-linux-glibc2.31
          
      - name: Install toolchain
        run: |
          curl -sOL https://more.musl.cc/x86_64-linux-musl/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
          rm aarch64-linux-musl-cross.tgz
          sudo cp -fpr aarch64-linux-musl-cross/* /usr/local/
          
      - name: Install gmp
        run: |
          curl -sOL https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz
          tar -xf gmp-6.3.0.tar.xz
          rm gmp-6.3.0.tar.xz
          cd gmp-6.3.0
          ./configure --disable-shared --build=x86_64-linux-gnu --host=aarch64-linux-musl
          make
          # make check
          sudo make install

      - name: Build runtime
        run: |
          PATH="$(pwd)/boot/bin:$PATH" make -C runtime LDFLAGS=-static BOOTSTRAP_STYLE=0 TARGET=aarch64-linux-musl TARGET_ARCH=arm64 WITH_GMP_DIR=/usr/local gdtoa/arithchk gdtoa/qnan gen/gen-types
          qemu-aarch64-static runtime/gen/gen-types ml-types.h > runtime/gen/ml-types.h
          cp -fpR runtime/gen/ml-types.h runtime/ml-types.h
          qemu-aarch64-static runtime/gen/gen-types c-types.h > runtime/gen/c-types.h
          cp -fpR runtime/gen/c-types.h runtime/c-types.h
          qemu-aarch64-static runtime/gen/gen-types c-types.sml > runtime/gen/c-types.sml
          qemu-aarch64-static runtime/gdtoa/arithchk > runtime/gdtoa/arith.h
          qemu-aarch64-static runtime/gdtoa/qnan > runtime/gdtoa/gd_qnan.h
          PATH="$(pwd)/boot/bin:$PATH" make LDFLAGS=-static BOOTSTRAP_STYLE=0 TARGET=aarch64-linux-musl TARGET_ARCH=arm64 WITH_GMP_DIR=/usr/local dirs
          PATH="$(pwd)/boot/bin:$PATH" make LDFLAGS=-static BOOTSTRAP_STYLE=0 TARGET=aarch64-linux-musl TARGET_ARCH=arm64 WITH_GMP_DIR=/usr/local runtime
          cp -fpR build/lib/mlton/targets/aarch64-linux-musl boot/lib/mlton/targets/

      - name: Build MLton
        run: |
          PATH="$(pwd)/boot/bin:$PATH" \
          make \
            LDFLAGS=-static BOOTSTRAP_STYLE=0 \
            TARGET=aarch64-linux-musl TARGET_ARCH=arm64 \
            WITH_GMP_DIR=/usr/local \
            OLD_MLTON_COMPILE_ARGS="-cc-opt -I/usr/local/include -link-opt '-static -L/usr/local/lib'" \
            MLTON_BINARY_RELEASE_WITH_DOCS=false \
            binary-release
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mlton-aarch64-linux-static-master
          path: ./*.tgz
