name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
        ref: ["on-20210117-release", "master"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: MLton/mlton
          ref: refs/heads/${{ matrix.ref }}

      - run: sudo apt-get install mlton
