name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
        ref: ["master"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: MLton/mlton
          ref: refs/heads/${{ matrix.ref }}

      - name: Install mlton
        run: |
          sudo apt-get update
          sudo apt-get install mlton

      - name: Install toolchain
        run: |
          curl -sO https://more.musl.cc/x86_64-linux-musl/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
          sudo cp -fpr aarch64-linux-musl-cross/* /usr/local/

      - name: Install gmp
        run: |
          curl -sO https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
          tar -xf gmp-6.3.0.tar.xz
          cd gmp-6.3.0
          ./configure --disable-shared --build=x86_64-linux-gnu --host=aarch64-linux-musl
          make
          sudo make install
