name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
        ref: ["master"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: MLton/mlton
          ref: refs/heads/${{ matrix.ref }}

      - run: |
          sudo apt-get update
          sudo apt-get install mlton
      - run: |
          curl -sO https://more.musl.cc/x86_64-linux-musl/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
          sudo cp -r aarch64-linux-musl-cross/* /
        
