name: build

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo'
        required: true
        default: 'MLton'
        type: string
      ref:
        description: 'git ref'
        required: true
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, arch_group: amd64, qemu: aarch64 }
          - { arch: aarch64, arch_group: arm64, qemu: aarch64 }
          - { arch: powerpc, arch_group: powerpc, qemu: ppc }

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}/mlton
          ref: refs/heads/${{ inputs.ref }}

      - name: Install system prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libgmp-dev qemu-user-static

      - name: Install toolchain
        run: |
          curl -sOL https://more.musl.cc/x86_64-linux-musl/${{ matrix.config.arch }}-linux-musl-cross.tgz
          tar -xf ${{ matrix.config.arch }}-linux-musl-cross.tgz
          rm ${{ matrix.config.arch }}-linux-musl-cross.tgz
          sudo cp -fpr ${{ matrix.config.arch }}-linux-musl-cross/* /usr/local/

      - name: Install gmp
        run: |
          curl -sOL https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz
          tar -xf gmp-6.3.0.tar.xz
          rm gmp-6.3.0.tar.xz
          cd gmp-6.3.0
          ./configure --disable-shared --build=x86_64-linux-gnu --host=${{ matrix.config.arch }}-linux-musl
          make
          # make check
          sudo make install

      - name: Install bootstrap mlton
        run: |
          mkdir boot && cd boot
          curl -sOL https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117-1.amd64-linux-glibc2.31.tgz
          tar xzf mlton-20210117-1.amd64-linux-glibc2.31.tgz --exclude='*/share'
          rm mlton-20210117-1.amd64-linux-glibc2.31.tgz
          mv mlton-20210117-1.amd64-linux-glibc2.31/* .
          rmdir mlton-20210117-1.amd64-linux-glibc2.31
          # Backport fixes
          cp ../runtime/platform/linux.h lib/mlton/include/platform/linux.h

          # Build target runtime
          curl -sOL https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117.src.tgz
          tar xzf mlton-20210117.src.tgz
          rm mlton-20210117.src.tgz
          mv mlton-20210117 src
          cp ../runtime/platform/linux.h src/runtime/platform/linux.h
          PATH="$(pwd)/bin:$PATH" make -C src LDFLAGS=-static BOOTSTRAP_STYLE=0 TARGET=${{ matrix.config.arch }}-linux-musl TARGET_ARCH=${{ matrix.config.arch_group }} WITH_GMP_DIR=/usr/local dirs
          PATH="$(pwd)/bin:$PATH" make -C src LDFLAGS=-static BOOTSTRAP_STYLE=0 TARGET=${{ matrix.config.arch }}-linux-musl TARGET_ARCH=${{ matrix.config.arch_group }} WITH_GMP_DIR=/usr/local runtime
          cp -fpR src/build/lib/mlton/targets/${{ matrix.config.arch }}-linux-musl lib/mlton/targets/

      - name: Build MLton
        run: |
          PATH="$(pwd)/boot/bin:$PATH" \
          make \
            BOOTSTRAP_STYLE=0 \
            TARGET=${{ matrix.config.arch }}-linux-musl TARGET_ARCH=${{ matrix.config.arch_group }} \
            OLD_MLTON_COMPILE_ARGS="-cc-opt -I/usr/local/include -link-opt '-static -L/usr/local/lib'" \
            dirs runtime compiler script basis-no-check libraries-no-check tools

          mv build/lib/mlton/targets/${{ matrix.config.arch }}-linux-musl build/lib/mlton/targets/self
          mv Makefile.binary build/Makefile
          mv build mlton-${{ inputs.ref }}.${{ matrix.config.arch }}-linux
          tar czvf mlton-${{ inputs.ref }}.${{ matrix.config.arch }}-linux.tgz mlton-${{ inputs.ref }}.${{ matrix.config.arch }}-linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mlton-${{ inputs.ref }}.${{ matrix.config.arch }}-linux
          path: ./*.tgz
